import os
from urllib.parse import quote_plus
from pymsaad.util import get_rand_hex

# DO NOT CHANGE. NEEDS TO BE AT TOP OF MODULE.
if not 'FLASK_PASS' in os.environ.keys():
    reg_info = dict()
    reg_info['secret'] = input('please enter your application password.')

########################################################################################################################
## FLASK ADMIN KEY: <CHANGE ME> ########################################################################################
# Arbitrary flask encryption seed. Pick something complicated.
SECRET_KEY = '1b1808b7-4417-47b0-9db0-1395f978ffff'

########################################################################################################################
## FLASK SSL CERTS: <CHANGE ME> ########################################################################################
# DO NOT USE THIS PACKAGE WITHOUT EITHER OF THESE. Follow step 1 in the Setup portion of the README.
CERT_PEM_ABS_PATH = os.path.realpath('./cert.pem')
KEY_PEM_ABS_PATH = os.path.realpath('./key.pem')

########################################################################################################################
## AAD CONFIG: #########################################################################################################
reg_info = {
    # <CHANGE ME>
    "tenant": "MYCOMPANY.onmicrosoft.com",

    # <CHANGE ME>
    "client_id": "11112222-aaaa-bbbb-cccc-ddddeeeeffff",
    # Aka Application ID. Generated by the Azure Portal during app registration.

    # <CHANGE ME OR CHANGE AZURE PORTAL>
    # Needs to be https & match the redircet uril specified during app registration at portal.azure.com.
    "redirect_uri": quote_plus("https://127.0.0.1:5000/getAToken"),
    "redirect_uri_plaintext": "https://127.0.0.1:5000/getAToken",
    # Tells the authority_host where to send the token.

    # <CHANGE ME>
    # "scope" is used by v2.0 of the Graph API. Needs to match to permissions you gave your app when registering with AAD.
    "scope" : quote_plus("https://graph.microsoft.com/Files.Read.All https://graph.microsoft.com/Sites.Read.All https://graph.microsoft.com/User.Read https://graph.microsoft.com/openid"),
    "scope_plaintext": "https://graph.microsoft.com/Files.Read.All https://graph.microsoft.com/Sites.Read.All https://graph.microsoft.com/User.Read https://graph.microsoft.com/openid",
    # This **example** scope lays out read/write access for Sharepoint and read-access for user info.

    # "resource" is used by v1.0 of the Graph API. Do not change.
    "resource": quote_plus("https://graph.microsoft.com"),
    "resource_plaintext": "https://graph.microsoft.com",

    # Do not change.
    "authority_host_url": "https://login.microsoftonline.com",

    # Essentially a session-id. Do not change.
    "state": get_rand_hex(30),
}

########################################################################################################################
## FINAL CHECKS: #######################################################################################################
# Everything will break if secret is not specified. Checks if the register already has a secret value assigned.
if 'secret' not in reg_info.keys():
    reg_info['secret'] = os.environ['FLASK_PASS']


